# Week 4 Problem Set

Each week you will have a problem set due on Sunday night before midnight.
You will download a template Jupyter notebook file (like this one) and complete all of your work in the file then save it with your last name in the following format:
lastname_week4ProblemSet.ipynb for example I would submit Zematis_week3ProblemSet.ipynb  

1. Create a 4 by 4 array containing the even integers from 2 thru 32. Create a second 4 by 4 array containing the integers 16 down to 1. Print both arrays you created and the print the output after multiplying both arrays

In [10]:
# Code for Problem 1
import numpy as np
# Create the first array containing even integers from 2 to 32

a=[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32]
a = np.array(a).reshape(4, 4)
# Create the second array containing integers from 16 to 1

b=[16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
b = np.array(b).reshape(4, 4)
# Display the first array
print('\nfirst array containing even integers from 2 to 32')

print(a)


# Display the second array
print('\nthe second array containing integers from 16 to 1')

print(b)

# Multiply both arrays
print('\nMultiply both arrays')

print(a*b)


first array containing even integers from 2 to 32
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

the second array containing integers from 16 to 1
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

Multiply both arrays
[[ 32  60  84 104]
 [120 132 140 144]
 [144 140 132 120]
 [104  84  60  32]]


2. Create a 2 by 3 array containing the first 6 powers of 2 beginning with 2 to the 0 power. Flatten the array first with method flatten, then with ravel. In each case, display the result then display the original array to show that it was unmodified.

In [11]:
# Code for Problem 2

# Create the array containing the first 6 powers of 2
a=[1, 2, 4, 8, 16, 32]
a = np.array(a).reshape(2, 3)
#print(a)
# Flatten the array using the flatten method
flattened_a = a.flatten()

# Flatten creates a copy of the array


# Display the flattened array
print('\nDisplay the flattened array')

print(flattened_a)

# Display the original array to show that it was unmodified
print('\nDisplay the original array to show that it was unmodified')

print(a)

# Ravel the array
raveled_a = a.ravel()

# Ravel creates a one dimensional view of the array


# Display the raveled array
print('\nDisplay the raveled array')

print(raveled_a)

# Display the original array to show that it was unmodified
print('\nDisplay the original array to show that it was unmodified')

print(a)


Display the flattened array
[ 1  2  4  8 16 32]

Display the original array to show that it was unmodified
[[ 1  2  4]
 [ 8 16 32]]

Display the raveled array
[ 1  2  4  8 16 32]

Display the original array to show that it was unmodified
[[ 1  2  4]
 [ 8 16 32]]


3. Create an array containing the values 1-15, reshape it into a 3 by 5 array, then use indexing and slicing techniques to perform each of the following operations (label and comment on each operation):
- Select row 2
- Select column 5
- Select rows 0 and 1
- Select the elements that is in row 1 column 4
- Select all elements from rows 1 and 2 that are in columns 0, 2 and 4

In [9]:
# Code for Problem 3
import numpy as np

# Create an array containing the values 1-15
arr = np.arange(1, 16)
print('\nCreate an array containing the values 1-15')

print(arr)


# Reshape the array into a 3 by 5 array
reshaped_arr = arr.reshape(3, 5)
print('\nReshape the array into a 3 by 5 array')

print(reshaped_arr)

# Select row 2
r2=reshaped_arr[1]
print('\nSelect row 2')

print(r2)

# Select column 5
print('\nSelect column 5')

c5=reshaped_arr[:,4]
print(c5)

# Select rows 0 and 1
r=reshaped_arr[0:2] 
print('\nSelect rows 0 and 1')

print(r)

# Select the element in row 1, column 4
e=reshaped_arr[0,3]
print('\nSelect the element in row 1, column 4')

print(e)

# Select all elements from rows 1 and 2 that are in columns 0, 2, and 4
ea= reshaped_arr[0:2, [0, 2, 4]]    
print('\nSelect all elements from rows 1 and 2 that are in columns 0, 2, and 4')

print(ea)


Create an array containing the values 1-15
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshape the array into a 3 by 5 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Select row 2
[ 6  7  8  9 10]

Select column 5
[ 5 10 15]

Select rows 0 and 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Select the element in row 1, column 4
4

Select all elements from rows 1 and 2 that are in columns 0, 2, and 4
[[ 1  3  5]
 [ 6  8 10]]


4. Create the two Numpy arrays below and then complete the following
-  Step 1: Use vertical stacking to create the 4 by 2 array named array3 with array1 stacked on top of array2
-  Step 2: Use horizontal stacking to create the 2 by 4 array named array4 with array2 to the right of array1
-  Step 3: Use vertical stacking with two copies of array4 to create a 4 by 4 array named array5
-  Step 4: Use horizontal stacking with two copies of array3 to create a 4 by 4 array named array6


In [12]:
# Code for Problem 4
import numpy as np
array1 = np.array([[1, 2],[3, 4]])
array2 = np.array([[5, 6],[7, 8]])

# Step 1
array3 = np.vstack((array1, array2))
print('\nStep 1')

print(array3)
# Step 2
array4 = np.hstack((array1, array2))
print('\nStep 2')
print(array4)
# Step 3
array5 = np.vstack((array4, array4))
print('\nStep 3')
print(array5)
# Step 4
array6 = np.hstack((array3, array3))
print('\nStep 4')
print(array6)


Step 1
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Step 2
[[1 2 5 6]
 [3 4 7 8]]

Step 3
[[1 2 5 6]
 [3 4 7 8]
 [1 2 5 6]
 [3 4 7 8]]

Step 4
[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]
 [7 8 7 8]]


In [14]:
# Code for Problem 5
import numpy as np
import pandas as pd
# Create DataFrame

temperatures = {
    'Name': ['Maxine', 'Maxine', 'Maxine', 'James', 'James', 'James', 'Amanda', 'Amanda', 'Amanda'],
    'Temperature': [25, 28, 30, 22, 25, 26, 27, 29, 30]
}

temperatures = pd.DataFrame(temperatures)

#print(type(tempatures))
# Recreate with custom indicies
print('\nRecreate with custom indicies')
custom_indices = ['Morning', 'Afternoon', 'Evening','Morning', 'Afternoon', 'Evening','Morning', 'Afternoon', 'Evening']
temperatures.index = custom_indices
print(temperatures)

# Select Maxine column
maxine_temperatures = temperatures[temperatures['Name'] == 'Maxine']['Temperature']
print('\nSelect Maxine column')
print(maxine_temperatures)

# Select morning row
m=temperatures.loc['Morning']
print('\nSelect morning row')
print(m)


# Select morning & evening
e=temperatures.loc[['Evening','Morning']]
print('\nSelect morning & evening')
print(e)
# Select Amanda and Maxine columns
manda_temperatures = temperatures[temperatures['Name'].isin(['Amanda', 'Maxine'])]
print('\nSelect Amanda and Maxine columns')
print(manda_temperatures)
# Select morning & afternoon for Amanda & Maxine
gg= manda_temperatures.loc[['Morning','Afternoon']]
print('\nSelect morning & afternoon for Amanda & Maxine')
print(gg)
# Use describe method on temperature
print('\nUse describe method on temperature')
stat = temperatures.describe()
print(stat)
# Transpose the temperature DataFrame
transposed_temperatures = temperatures.T
print('\nTranspose the temperature DataFrame')
print(transposed_temperatures)
# Sort temperature
tsort=temperatures.sort_values(by='Name')
print('\nSort temperature')
print(tsort)


Recreate with custom indicies
             Name  Temperature
Morning    Maxine           25
Afternoon  Maxine           28
Evening    Maxine           30
Morning     James           22
Afternoon   James           25
Evening     James           26
Morning    Amanda           27
Afternoon  Amanda           29
Evening    Amanda           30

Select Maxine column
Morning      25
Afternoon    28
Evening      30
Name: Temperature, dtype: int64

Select morning row
           Name  Temperature
Morning  Maxine           25
Morning   James           22
Morning  Amanda           27

Select morning & evening
           Name  Temperature
Evening  Maxine           30
Evening   James           26
Evening  Amanda           30
Morning  Maxine           25
Morning   James           22
Morning  Amanda           27

Select Amanda and Maxine columns
             Name  Temperature
Morning    Maxine           25
Afternoon  Maxine           28
Evening    Maxine           30
Morning    Amanda           27
Aft